### ISSUE TITLE
ASVS Checklist Excel Formulae

### ISSUE THREAD

**Issue by JonathanBroomeMYOB** [shenril/owasp-asvs-checklist#2]
Hello,

I noticed that in `ASVS-checklist-en.xlsx`, the formulae for some of the categories are not correctly computing the score.

This happens in three places that I am aware of:

1. Architecture
The formula for _Valid criteria_ is as follows:
`=0+COUNTIF(Architecture!D2:D11,"Valid")`
But the formula for _Total criteria_ is:
`=COUNTIF(Architecture!D2:D12,"<>Not Applicable")`
Notice the final cell differs by one value.

2. Error handling and logging
The formula for _Valid criteria_ is as follows:
`=COUNTIF('Error Handling and Logging'!D2:D13,"Valid")`
But the formula for _Total criteria_ is:
`=COUNTIF('Error Handling and Logging'!D2:D14,"<>Not Applicable")`

3. Configuration
The same as above, _Valid criteria_ is:
`=COUNTIF(Configuration!D2:D10,"Valid")`
But _Total criteria_ is:
`=COUNTIF(Configuration!D2:D11,"<>Not Applicable")`

Steps to reproduce:
1. On each page of the document (except the _ASVS Results_ page)
Put "Valid" in every cell of the "Valid" column in the table
2. Return to the _ASVS Results_ page
3. All _Validity Percentage_ entries should be 100%

 

Note: I have not checked the ODS file for similar issues.

**Comment by shenril** [comment]
Thank for you feedback 
I correct the xlsx
