### ISSUE TITLE
Upgrade to ASVS 4.0

### ISSUE THREAD

**Issue by shenril** [shenril/owasp-asvs-checklist#3]
https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project

Please note there will not be a 3.1 release and we will be going directly from ASVS 3.0.1 to 4.0 in February 2019!

I will upgrade the sheets once the new version is out

**Comment by shenril** [comment]
Version 4.0.1 was published on March 3rd
I'll wait a week to see if minor versions come out and update this project

**Comment by lyz-code** [comment]
@shenril are you working on it? or you accept PR?

**Comment by shenril** [comment]
Hello @lyz-code , I'm currently working on it 
I was just waiting to see if new minor version would come out but seems stable so I'll push 4.0 soon

**Comment by lyz-code** [comment]
I needed to use it so I upgraded it anyway... Check if it works for you @shenril 

https://github.com/shenril/owasp-asvs-checklist/pull/6

**Comment by shenril** [comment]
This is done ! 
I created the v4.0.1 release with both files updated
